pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
        DATABASE_URI = 
    }
    stages {
        stage('Setup') {
	        steps {
	    	    sh "bash jenkins/setup.sh"
            }
        }
        stage('Testing') {
	        steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
	    	        sh "bash jenkins/test.sh"
                }
            }
        }
        stage('Push') {
	        steps {
	    	    sh "docker-compose push"
            }
        }
        stage('Build') {
            steps {
		        sh "docker-compose build"
            }
        }
	    stage('Network') {
	        steps {
	    	    sh "if ! docker network inspect my-overlay-network > /dev/null 2>&1; then docker network create -d overlay my-overlay-network; fi" 
            }
        }
        stage('Deploy') {
            steps {
                sh "docker stack deploy --compose-file docker-compose.yaml workoutapp-stack"
            }
        }
    }
}