pipeline {
    agent any
    environment {
        DATABASE_URI = credentials("DATABASE_URI")
        MYSQL_DATABASE = ("MYSQL_DATABASE")
        MYSQL_USER = ("MYSQL_USER")
        MYSQL_PASSWORD = ("MYSQL_PASSWORD")
        MYSQL_ROOT_PASSWORD = ("MYSQL_ROOT_PASSWORD")
    }
    stages {
        stage('Setup') {
	        steps {
	    	    sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
	        steps {
	    	    sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Screamzle/DevOps-Project']]])
		        sh "bash jenkins/build.sh"
            }
        }
	    stage('Network') {
	        steps {
	    	    sh "if ! docker network inspect my-overlay-network > /dev/null 2>&1; then docker network create my-overlay-network; fi" 
            }
        }
        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
    }
}