pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
    }
    stages {
        stage('Setup') {
	        steps {
	    	    sh "bash jenkins/setup.sh"
            }
        }
        stage('Testing') {
	        steps {
	    	    sh "bash jenkins/test.sh"
                junit 'junit_report.xml'
                }
            }
        }
        stage('Build') {
            steps {
		        sh "docker-compose build"
            }
        }
        stage('Push') {
	        steps {
	    	    sh "docker-compose push"
            }
        }
        stage('Deploy') {
            steps {
                sh "docker stack deploy --compose-file docker-compose.yaml workoutapp-stack"
            }
        }
    }
}